### ISSUE TITLE
Problems using StreamHandler

### ISSUE THREAD

**Issue by meckhardt** [guzzle/streams#27]
Recently I noticed a strange behavior when using StreamHandler. `Stream::feof` sometimes returns `false`. 

Another issue is, that the configured timeout applies to each `Stream::read` request, which could lead to a performance issue.

I have created a small test script that prepares the stream context like it is done by guzzle. The relevant part, that takes very long is extracted from GuzzleHttp\Stream\Utils class.

```php
<?php

require 'vendor/autoload.php';

// First create stream context, like it is done via StreamHandler.
$url = 'http://servedby.flashtalking.com/imp/2/31983;777670;208;xml;SevenOneDE;PrerollTest/?cachebuster=1276372172';

$options = [
    'http' => [
        'allow_self_signed' => true,
        'cafile' => __DIR__.'./vendor/guzzlehttp/guzzle/src/cacert.pem',
        'follow_location' => 0,
        'header' => 'Host: servedby.flashtalking.com
cookie: flashtalkingad1="GUID=2477EAD3F22045"
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
accept: */*
cache-control: no-cache
Connection: close',
        'ignore_errors' => false,
        'method' => 'GET',
        'protocol_version'    => '1.1',
        'timeout' => 4,
        'verify_peer' => false,
    ],
];

$context = stream_context_create($options, []);

// Create the streams.
$source  = \GuzzleHttp\Stream\Stream::factory(fopen($url, 'r', null, $context));
$dest    = \GuzzleHttp\Stream\Stream::factory(fopen('php://temp', 'w+'));

// Copied part from https://github.com/guzzle/streams/blob/master/src/Utils.php#L61
while (!$source->eof()) {
    if (!$dest->write($source->read(1048576))) {
        break;
    }
}
```

Data is red from `$source` and written to `$dest`. But sometimes `$source->eof()` returns `false`, although all data was already red from `$source`. Due to having a condition on how many data was written, the loop does not run infinitive. Nevertheless the `Stream::read` is called twice with the given timeout. In my case it took me 8 seconds then, until the data was fully red.

At the moment I don't know if it is related to a PHP issue or a strange webserver / proxy implementation used by servedby.flashtalking.com host.

My current solution is to switch to `CurlHandler`.

Should such issues been handled by the GuzzleHttp\Stream\Utils? What do you mean.

Regards,
Martin

**Comment by mtdowling** [comment]
> Stream::feof sometimes returns false.

Guzzle just wraps the underlying stream. If the PHP stream returns false then Guzzle returns false. See https://github.com/guzzle/streams/blob/master/src/Stream.php#L212.

> Another issue is, that the configured timeout applies to each Stream::read request, which could lead to a performance issue.

This is also outside of Guzzle's control and just how PHP streams work.
