### ISSUE TITLE
Unable to read/write sockets using hhvm

### ISSUE THREAD

**Issue by FabioBatSilva** [guzzle/streams#31]
When reading or writing to a socket using hhvm [Stream](https://github.com/guzzle/streams/blob/master/src/Stream.php#L166) does not try to [read](https://github.com/guzzle/streams/blob/master/src/Stream.php#L236) or [write](https://github.com/guzzle/streams/blob/master/src/Stream.php#L244).
This is probability hhvm fault in provide the correct `mode`, 
but `Stream` could just call fread/fwrite instead of trying to find out whether or not the stream is readable/writable.

``` php
$uri    = 'tcp://127.0.0.1:8087';
$socket = stream_socket_client($uri);
$stream = new \GuzzleHttp\Stream\Stream($socket);

$stream->read($length);
// false

fread($socket, $length);
// message-content

/*
stream_get_meta_data($socket);
{
    "wrapper_type": "File",
    "stream_type": "tcp_socket/ssl",
    "mode": "",
    "unread_bytes": 0,
    "seekable": false,
    "uri": "",
    "timed_out": false,
    "blocked": false,
    "eof": false,
    "wrapper_data": null
}
*/
```

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now.
