### ISSUE TITLE
getContents() only works once

### ISSUE THREAD

**Issue by georaldc** [guzzle/streams#34]
Is there a reason why getContents() cannot be called more than once? I see that because it uses stream_get_contents(), the stream file pointer position gets moved to the end and thus, prevents successive calls to this method. I guess rewinding the fp position would work but maybe there's a reason why this wasn't done?

**Comment by mtdowling** [comment]
`getContents` is not meant to maintain the cursor position in the file. It changes the cursor position and mirrors what stream_get_contents does. If you need the position to be maintained, then you would need to do that in your code that uses a Guzzle stream.

**Comment by AndreKR** [comment]
In a `CachingStream` is is unexpected, isn't it?
