### ISSUE TITLE
 Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in  .../vendor/php-http/discovery/src/StreamFactoryDiscovery.php on line 25

### ISSUE THREAD

**Issue by vusisindane** [guzzle/streams#36]
I'm using this package with mailgun.  seems to be working on my localhost, but when deployed to a test server, I get this error:

/home4/vusisind/public_html/skybookings_test/wp-content/themes/eventify/code/vendor/php-http/discovery/src/StreamFactoryDiscovery.php on line 25
[18-Aug-2016 23:50:27 UTC] PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in .../vendor/php-http/discovery/src/StreamFactoryDiscovery.php on line 25

I thought it was because I"m running different versions of PHP on my localhost and on test server.  I changed them to be identical, and I'm still having the same error.

please help

**Comment by davidkslack** [comment]
Same issue. 
Local host working with PHP v5.6
Dev server failing. 
Dev server is on PHP v5.6 on a "php -v" but on checking the browser phpinfo I find it is on PHP v5.4!

I think the fix (for me) is making sure the Dev server is on at least PHP v5.6 and the Live server is on the same.

Hope this helps somone

**Comment by mtdowling** [comment]
This is due to running an older version of PHP. Make sure you're using PHP 5.4 or greater. You may be running into some path issue.

**Comment by Protossoario** [comment]
I am having this exact issue, running PHP 5.6, while trying to get Mailgun set up. Is there any solution? I'm pretty sure it's not a pathing issue.
