### ISSUE TITLE
Stream: unexpected side effect in __toString() implementation

### ISSUE THREAD

**Issue by NoiseByNorthwest** [guzzle/streams#37]
In Stream class, __toString() and getContent() methods have side effects on receiver stream.
Since this is a poor OO design practice, which is furthermore error prone, is it possible (in a future major) to  remove this behavior (i.e. to replace it by something like "readBody()") ?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now.
